### ISSUE TITLE
Good job 🎉

### ISSUE THREAD

**Issue by jeremyfl** [sonadztux/Logical-Solving-Rekrutasi-DASPRO-LumpiaBasah#1]
Thank you for all of your efforts to participate in DASPRO recruitment.

I just want to let you know that we have 3 tier in our class, and congratulate that you're potential to join the first class tier, as you know the first-class tier is exclusive, hence you should prepare yourself to practice and study a lot from the best practice than other classes do.

Just let me know if you are interested.

**Comment by sonadztux** [comment]
You're welcome, kak @jeremylombogia.

Woah, thank you very much for this offer. Absolutely, yes I'm in! I'm ready to practice and learn more.

But, one question, this offer is only valid for me or also valid for all my friends in LumpiaBasah (Group 10)?
